- devchat/requirements.txt
- Added urllib3 with version constraint <2.0 to devchat/requirements.txt.
Resolve the version mismatch error between urllib3 2.0 and OpenSSL
> Add urllib3<2.0 to requirements.txt

- devchat/openai/openai_prompt.py
- Extract finish_reason from choice in OpenAIPrompt.
- Append finish_reason to delta_content if present.
> Add finish_reason to OpenAIPrompt response

- devchat/openai/openai_prompt.py
- Update the role check in the `history_chat` state of the `OpenAIPrompt` class to include the "function" role.
- Previously, the role check only included "user" and "assistant" roles.
- This fix ensures that messages with the "function" role are correctly appended to the history messages.
- Also, update the role check in the `request` assignment to include the "function" role.
- Previously, the role check only included "user" role.
- This fix ensures that the last user message with the "function" role is correctly assigned as the request message.
> Fix role check in OpenAIPrompt class

- devchat/openai/openai_prompt.py
- Update the role check in the `history_chat` state of the `OpenAIPrompt` class to include the "function" role.
- Previously, the role check only included "user" and "assistant" roles.
- This update ensures that messages with the "function" role are correctly appended to the history messages.
- Also, update the role check in the `request` assignment to include the "function" role.
- Previously, the role check only included "user" role.
- This update ensures that the last user message with the "function" role is correctly assigned as the request message.
> Update role check in OpenAIPrompt class

- devchat/assistant.py
Fix for errors on windows.
- Check if 'id' and 'index' keys are present in chunk or choices.
- If not present, add 'id' and 'index' keys with appropriate values.
> Fix issue with missing 'id' and 'index' keys in chunk

- devchat/ide/vscode_services.py
This PR addresses the issue where the `selected_lines` function from the `devchat.ide.vscode_services` module was returning an object with an empty `filePath` field. Changes have been made to ensure that the function now correctly populates the `filePath` in the returned object, allowing for proper further processing and integration with development environments.
Closes https://github.com/devchat-ai/devchat/issues/253
> Fix empty filePath return issue in selected_lines function

- devchat/ide/service.py
- tests/test_cli_log.py
- tests/test_cli_prompt.py
This pull request includes several improvements to the `IDEService` aimed at enhancing developer experience and code clarity:
- Return types of certain methods are now accompanied by `LocationWithText` for increased specificity.
- The documentation of methods has been expanded to include examples and detailed descriptions of the command names involved.
- A new logging method description has been introduced to provide better guidance for developers.
These changes should improve the overall comprehensibility and utility of the `IDEService` interface. Please review the changes and provide feedback.
> Feature enhancement for IDEService with detailed comments and documentation

- devchat/engine/recursive_prompter.py
- devchat/engine/router.py
This pull request introduces two key enhancements to the parsing of `prompt.txt` files used in our workflow processes. It addresses the issues outlined in https://github.com/devchat-ai/devchat/issues/276 by improving path resolution and adding support for the `@file@` syntax within the content of `prompt.txt`.
- **Path Resolution:** We've fixed the issue where the parser was failing to accurately locate `prompt.txt`. The use of `os.path.expanduser` ensures that user directories are correctly resolved, enhancing the reliability of path access across different environments.
- **@file@ Syntax Support:** The new parsing logic recognizes and substitutes the `@file@` tags with the content of the actual files referenced. This allows for more dynamic and flexible workflow scripting, as files can …
> Enhance `prompt.txt` parsing: Path resolution fix and @file@ syntax support

- devchat/openai/openai_prompt.py
- tests/test_openai_prompt.py
This PR addresses issue #278 by adjusting the model validation severity from an error to a warning level. The modification will allow our system to log warnings instead of errors when there is a discrepancy between the requested and the received model from OpenAI's API.
Changes included:
- Updated validation logic to emit warnings instead of raising exceptions.
- Enhanced operational stability to accommodate model discrepancies.
- Increased system flexibility for future model updates from OpenAI.
This change aligns with the proposed solution in the original issue, aiming to improve system resilience and reduce unnecessary disruptions in service due to strict model validation.
By merging this PR, we can expect an improved integration experience with OpenAI's API that gracefully handles …
> Feature: Downgrade model validation severity to warnings

- devchat/_cli/run.py
This pull request addresses issue #306 by ensuring that when the `unit_test` command is entered into the chat input without any arguments, the system now provides the user with instructions on effective usage. These changes enhance usability by guiding new users or those unfamiliar with the command, allowing them to quickly learn and apply it correctly without manually searching through the documentation.
The functionality to filter out hidden workflows has been refactored as a part of this improvement. Below are the main changes included in this pull request:
- Remove handling of hidden workflows in the configuration logic.
- Eliminate unused functions related to default config file creation and reading hidden workflows.
- Simplify the command listing process with no filtering of hidden …
> Expose unit_test Command in Chat and Display Usage Instructions

- devchat/engine/command_runner.py
This pull request addresses the issue reported in devchat-ai/devchat#313, where the README was incorrectly marked with an error when a workflow requiring user input was triggered without it. The changes made ensure that the README is now displayed normally, without any inaccurate error indications, aligning with the expected behavior outlined in the issue.
The following improvements were made:
- README is now shown normally without redirecting to the error stream.
- User experience is enhanced by eliminating misleading error markings.
- Compliance with expected output as documented in the issue.
Closes devchat-ai/devchat#313.
> Fix README Error Marking When Workflow Triggered Without User Input

- devchat/llm/chat.py
- tests/test_cli_prompt.py
This PR addresses the issue where the `chat_json` decorator would inadvertently mutate the `PROMPT` template variable during multiple invocations within the devchat application, leading to inconsistent behavior as documented in issue [#354](https://github.com/devchat-ai/devchat/issues/354).
The proposed changes introduce a new variable `prompt_new` to hold the intermediary states, ensuring that the original `PROMPT` template remains unaffected across function calls. Both `chat` and `chat_json` functions have been updated to make use of `prompt_new`, providing a consistent and predictable outcome regardless of the number of invocations.
Closes devchat-ai/devchat#354.
> Fix chat_json decorator PROMPT mutation in devchat

- devchat/_cli/__init__.py
- devchat/llm/openai.py
This pull request includes two key improvements to the CLI:
- A new cache directory for Tiktoken has been added during the CLI initialization process to enhance performance and persistence.
- The request handler now explicitly uses `response_format` to return results in JSON format, ensuring consistency in response data structures.
These enhancements should provide a more robust and reliable user experience.
Please review the changes and let me know if there are any concerns or further optimizations we can implement.
> Implement Tiktoken cache directory and JSON response formatting

- devchat/engine/util.py
- devchat/llm/openai.py
- devchat/openai/http_openai.py
- devchat/openai/openai_chat.py
This pull request introduces a new setting for devchat_proxy.
> Add devchat_proxy setting

- devchat/assistant.py
- devchat/openai/http_openai.py
This PR includes a refactoring of the `stream_response` function to improve error handling and raise exceptions when necessary. Additionally, a new `devchat_proxy` setting has been introduced.
- Refactored `stream_response` function to handle error responses better and raise exceptions
- Added `devchat_proxy` setting to configure proxy for devchat
> Refactor stream_response and add devchat_proxy setting

- devchat/llm/openai.py
This PR includes modifications to the `content_to_json` function that allow it to handle non-JSON content gracefully. A helper function `_try_remove_markdown_block_flag` has been introduced to preprocess content for compatibility with older versions of the devchat-api.
> fix: Enhance content_to_json for backward compatibility

- devchat/llm/openai.py
- devchat/llm/pipeline.py
This PR introduces additional logging for the IDEService within the OpenAI and pipeline modules to enhance debugging and operational insights.
> chore: Add logging to IDEService in OpenAI and pipeline modules

- devchat/__main__.py
Refactoring `__main__.py` to disable `windows_expand_args` in the `_main` function for better command-line argument handling on Windows systems.
> Refactor main entrypoint to disable windows_expand_args

- devchat/_cli/log.py
This PR refactors the log.py file in the CLI to support file paths as an `insert` parameter. When a file path is supplied, the content is read into `insert` and the file is subsequently deleted.
___
enhancement
___
This PR enhances the log.py file in the CLI to support file paths as an `insert` parameter.
It introduces a new functionality where if the `insert` parameter is a file path, the content is read and assigned to the `insert` variable, and the file is deleted after its content is read.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>log.py</strong><dd><code>Enhanced log.py for file insertions handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Refactor log.py for file insertions handling in CLI

- devchat/openai/http_openai.py
This pull request adds SSL context to HTTPS connection in http_openai.py.
> Add SSL context to HTTPS connection in http_openai.py

- devchat/llm/chat.py
- devchat/llm/openai.py
- devchat/llm/pipeline.py
- devchat/openai/http_openai.py
This pull request addresses error handling improvements in the chat modules and stream functions. It includes the following changes:
- Commit c4f1971fc17fd72659a93631a36a46fcac97e394: Standardized error handling in chat modules by simplifying error reporting, consistently raising original exceptions, and streamlining error output for clarity.
- Commit 6c3b9328e4177df72ab44b07ce32efe4354f9361: Optimized error handling in stream_response and stream_request by improving error messages, adding exception handling, and refactoring conditional logic for cleaner code.
> Standardize and Optimize Error Handling in Chat Modules and Stream Functions

- devchat/assistant.py
This PR addresses the issue of handling empty choices in OpenAI responses. The changes include:
- Adding a check for non-empty choices array in the response
- Moving processing logic inside the non-empty check
- Improving error handling for malformed responses
These updates will enhance the robustness of our OpenAI integration and prevent potential errors when dealing with unexpected response formats.
> fix: Handle empty choices in OpenAI response

- devchat/_service/route/workflows.py
Correct the return statement in `update_custom_workflows` to explicitly pass `False` for the `updated` field and provide a clearer message for the `message` field. This change ensures consistent return type and improves the readability of the status messages.
> fix(devchat): correct update_custom_workflows return statements

- devchat/llm/openai.py
- devchat/llm/pipeline.py
- devchat/openai/http_openai.py
This pull request includes several improvements to the OpenAI API integration within the project. The key changes are as follows:
1. **Refactored Logging**: Improved the logging format for OpenAI API errors to enhance readability and debugging capabilities.
2. **Code Readability**: Enhanced code readability by refactoring the `http_openai` and `pipeline` modules and adding comprehensive docstrings.
3. **JSON Parsing Fix**: Addressed a critical issue by allowing non-strict JSON parsing and ensuring that the first argument is returned in the pipeline.
4. **Error Handling**: Enhanced error handling and logging mechanisms within the `http_openai` and `pipeline` for better resilience and maintainability.
These changes aim to make the codebase more robust and easier to maintain moving forward. …
> Improve OpenAI API Integration: Refactor and Error Handling Enhancements

- devchat/_cli/run.py
- devchat/_cli/utils.py
- devchat/_service/route/workflows.py
- devchat/utils.py
- devchat/workflow/update_util.py
This PR improves directory deletion on Windows by implementing a custom rmtree function to handle Windows-specific deletion errors. The changes include:
- Implementing a custom rmtree function to handle Windows deletion errors
- Replacing shutil.rmtree calls with the new rmtree utility function
- Moving the __onerror handler to utils.py for centralized error handling
These changes should resolve issues related to directory deletion on Windows systems and improve overall reliability of the deletion process.
> fix: Improve directory deletion on Windows

- devchat/_service/route/workflows.py
This pull request implements a new feature to add a toggle for public workflow updates. The changes include:
- Implement config-based control for workflow updates
- Check for valid API keys before updating workflows
- Add conditional logic to skip updates if disabled
These changes provide more flexibility and control over workflow updates, ensuring that updates only occur when desired and with proper authentication.
> feat: Add toggle for public workflow updates

- devchat/workflow/env_manager.py
This pull request enhances the PyEnvManager with improved environment handling capabilities. The changes include:
- Refactoring environment creation and dependency management
- Adding support for updating existing environments
- Implementing separate removal methods for different environment types
These improvements will provide more flexibility and better control over Python environments within our project.
> feat: Enhance PyEnvManager with improved environment handling

- devchat/llm/openai.py
This pull request introduces a new feature for the LLM API by adding a configurable `max_tokens` setting. Changes include:
- Implemented loading of chat configuration from a YAML file.
- Introduced `get_maxtokens_by_model` function to retrieve `max_tokens` based on model selection.
- Updated chat completion functions to utilize the dynamic `max_tokens` setting.
This enhancement aims to provide more flexibility in managing the token limits for different models, improving the overall functionality of the API.
Closes <user>/<repo>#issue_id
> Add max_tokens configuration for LLM API
